// Generated by https://quicktype.io

export interface AstronomyAPI {
    next:      Next;
    siguiente: Siguiente;
    results:   Result[];
}

export interface Next {
    page:  number;
    limit: number;
}

export interface Result {
    explanation: string;
    hdurl?:      string;
    title:       string;
    url:         string;
}

export interface Siguiente {
    siguiente: string;
}


